// Copyright (c) 2017 Jan Pluskal, Viliam Letavay
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Text;
using Thrift.Protocol;

namespace Netfox.Snoopers.SnooperMessenger.Protocol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class LocationAttachement : TBase
  {
    private Coordinates _Coordinates;
    private bool _IsCurrentLocation;
    private long _PlaceID;

    public Coordinates Coordinates
    {
      get
      {
        return _Coordinates;
      }
      set
      {
        __isset.Coordinates = true;
        this._Coordinates = value;
      }
    }

    public bool IsCurrentLocation
    {
      get
      {
        return _IsCurrentLocation;
      }
      set
      {
        __isset.IsCurrentLocation = true;
        this._IsCurrentLocation = value;
      }
    }

    public long PlaceID
    {
      get
      {
        return _PlaceID;
      }
      set
      {
        __isset.PlaceID = true;
        this._PlaceID = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Coordinates;
      public bool IsCurrentLocation;
      public bool PlaceID;
    }

    public LocationAttachement() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                Coordinates = new Coordinates();
                Coordinates.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Bool) {
                IsCurrentLocation = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I64) {
                PlaceID = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("LocationAttachement");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (Coordinates != null && __isset.Coordinates) {
          field.Name = "Coordinates";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          Coordinates.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.IsCurrentLocation) {
          field.Name = "IsCurrentLocation";
          field.Type = TType.Bool;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(IsCurrentLocation);
          oprot.WriteFieldEnd();
        }
        if (__isset.PlaceID) {
          field.Name = "PlaceID";
          field.Type = TType.I64;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(PlaceID);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("LocationAttachement(");
      bool __first = true;
      if (Coordinates != null && __isset.Coordinates) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Coordinates: ");
        __sb.Append(Coordinates== null ? "<null>" : Coordinates.ToString());
      }
      if (__isset.IsCurrentLocation) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("IsCurrentLocation: ");
        __sb.Append(IsCurrentLocation);
      }
      if (__isset.PlaceID) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("PlaceID: ");
        __sb.Append(PlaceID);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
