// Copyright (c) 2017 Jan Pluskal, Viliam Letavay
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */

using System;
using System.Text;
using Thrift.Protocol;

namespace Netfox.Snoopers.SnooperMessenger.Protocol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MNMessagesSyncThreadKey : TBase
  {
    private long _OtherUserFbId;
    private long _ThreadFbId;

    public long OtherUserFbId
    {
      get
      {
        return _OtherUserFbId;
      }
      set
      {
        __isset.OtherUserFbId = true;
        this._OtherUserFbId = value;
      }
    }

    public long ThreadFbId
    {
      get
      {
        return _ThreadFbId;
      }
      set
      {
        __isset.ThreadFbId = true;
        this._ThreadFbId = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool OtherUserFbId;
      public bool ThreadFbId;
    }

    public MNMessagesSyncThreadKey() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.I64) {
                OtherUserFbId = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I64) {
                ThreadFbId = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("MNMessagesSyncThreadKey");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.OtherUserFbId) {
          field.Name = "OtherUserFbId";
          field.Type = TType.I64;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(OtherUserFbId);
          oprot.WriteFieldEnd();
        }
        if (__isset.ThreadFbId) {
          field.Name = "ThreadFbId";
          field.Type = TType.I64;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ThreadFbId);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("MNMessagesSyncThreadKey(");
      bool __first = true;
      if (__isset.OtherUserFbId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OtherUserFbId: ");
        __sb.Append(OtherUserFbId);
      }
      if (__isset.ThreadFbId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ThreadFbId: ");
        __sb.Append(ThreadFbId);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
