// Copyright (c) 2017 Jan Pluskal, Viliam Letavay
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Text;
using Thrift.Protocol;

namespace Netfox.SnooperMessenger.Protocol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MNMessagesSyncAppAttributionVisibility : TBase
  {
    private bool _HideAttribution;
    private bool _HideInstallButton;
    private bool _HideReplyButton;
    private bool _DisableBroadcasting;
    private bool _HideAppIcon;

    public bool HideAttribution
    {
      get
      {
        return _HideAttribution;
      }
      set
      {
        __isset.HideAttribution = true;
        this._HideAttribution = value;
      }
    }

    public bool HideInstallButton
    {
      get
      {
        return _HideInstallButton;
      }
      set
      {
        __isset.HideInstallButton = true;
        this._HideInstallButton = value;
      }
    }

    public bool HideReplyButton
    {
      get
      {
        return _HideReplyButton;
      }
      set
      {
        __isset.HideReplyButton = true;
        this._HideReplyButton = value;
      }
    }

    public bool DisableBroadcasting
    {
      get
      {
        return _DisableBroadcasting;
      }
      set
      {
        __isset.DisableBroadcasting = true;
        this._DisableBroadcasting = value;
      }
    }

    public bool HideAppIcon
    {
      get
      {
        return _HideAppIcon;
      }
      set
      {
        __isset.HideAppIcon = true;
        this._HideAppIcon = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool HideAttribution;
      public bool HideInstallButton;
      public bool HideReplyButton;
      public bool DisableBroadcasting;
      public bool HideAppIcon;
    }

    public MNMessagesSyncAppAttributionVisibility() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Bool) {
                HideAttribution = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.Bool) {
                HideInstallButton = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.Bool) {
                HideReplyButton = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.Bool) {
                DisableBroadcasting = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.Bool) {
                HideAppIcon = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("MNMessagesSyncAppAttributionVisibility");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.HideAttribution) {
          field.Name = "HideAttribution";
          field.Type = TType.Bool;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(HideAttribution);
          oprot.WriteFieldEnd();
        }
        if (__isset.HideInstallButton) {
          field.Name = "HideInstallButton";
          field.Type = TType.Bool;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(HideInstallButton);
          oprot.WriteFieldEnd();
        }
        if (__isset.HideReplyButton) {
          field.Name = "HideReplyButton";
          field.Type = TType.Bool;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(HideReplyButton);
          oprot.WriteFieldEnd();
        }
        if (__isset.DisableBroadcasting) {
          field.Name = "DisableBroadcasting";
          field.Type = TType.Bool;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(DisableBroadcasting);
          oprot.WriteFieldEnd();
        }
        if (__isset.HideAppIcon) {
          field.Name = "HideAppIcon";
          field.Type = TType.Bool;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(HideAppIcon);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("MNMessagesSyncAppAttributionVisibility(");
      bool __first = true;
      if (__isset.HideAttribution) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HideAttribution: ");
        __sb.Append(HideAttribution);
      }
      if (__isset.HideInstallButton) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HideInstallButton: ");
        __sb.Append(HideInstallButton);
      }
      if (__isset.HideReplyButton) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HideReplyButton: ");
        __sb.Append(HideReplyButton);
      }
      if (__isset.DisableBroadcasting) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DisableBroadcasting: ");
        __sb.Append(DisableBroadcasting);
      }
      if (__isset.HideAppIcon) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("HideAppIcon: ");
        __sb.Append(HideAppIcon);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
