// Copyright (c) 2017 Jan Pluskal, Viliam Letavay
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Text;
using Thrift.Protocol;

namespace Netfox.SnooperMessenger.Protocol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MNMessagesSyncDeltaReadReceipt : TBase
  {
    private MNMessagesSyncThreadKey _ThreadKey;
    private long _ActorFbId;
    private long _ActionTimestampMs;
    private long _WatermarkTimestampMs;

    public MNMessagesSyncThreadKey ThreadKey
    {
      get
      {
        return _ThreadKey;
      }
      set
      {
        __isset.ThreadKey = true;
        this._ThreadKey = value;
      }
    }

    public long ActorFbId
    {
      get
      {
        return _ActorFbId;
      }
      set
      {
        __isset.ActorFbId = true;
        this._ActorFbId = value;
      }
    }

    public long ActionTimestampMs
    {
      get
      {
        return _ActionTimestampMs;
      }
      set
      {
        __isset.ActionTimestampMs = true;
        this._ActionTimestampMs = value;
      }
    }

    public long WatermarkTimestampMs
    {
      get
      {
        return _WatermarkTimestampMs;
      }
      set
      {
        __isset.WatermarkTimestampMs = true;
        this._WatermarkTimestampMs = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ThreadKey;
      public bool ActorFbId;
      public bool ActionTimestampMs;
      public bool WatermarkTimestampMs;
    }

    public MNMessagesSyncDeltaReadReceipt() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                ThreadKey = new MNMessagesSyncThreadKey();
                ThreadKey.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I64) {
                ActorFbId = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I64) {
                ActionTimestampMs = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I64) {
                WatermarkTimestampMs = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("MNMessagesSyncDeltaReadReceipt");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ThreadKey != null && __isset.ThreadKey) {
          field.Name = "ThreadKey";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          ThreadKey.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (__isset.ActorFbId) {
          field.Name = "ActorFbId";
          field.Type = TType.I64;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ActorFbId);
          oprot.WriteFieldEnd();
        }
        if (__isset.ActionTimestampMs) {
          field.Name = "ActionTimestampMs";
          field.Type = TType.I64;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ActionTimestampMs);
          oprot.WriteFieldEnd();
        }
        if (__isset.WatermarkTimestampMs) {
          field.Name = "WatermarkTimestampMs";
          field.Type = TType.I64;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(WatermarkTimestampMs);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("MNMessagesSyncDeltaReadReceipt(");
      bool __first = true;
      if (ThreadKey != null && __isset.ThreadKey) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ThreadKey: ");
        __sb.Append(ThreadKey== null ? "<null>" : ThreadKey.ToString());
      }
      if (__isset.ActorFbId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ActorFbId: ");
        __sb.Append(ActorFbId);
      }
      if (__isset.ActionTimestampMs) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ActionTimestampMs: ");
        __sb.Append(ActionTimestampMs);
      }
      if (__isset.WatermarkTimestampMs) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("WatermarkTimestampMs: ");
        __sb.Append(WatermarkTimestampMs);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
