// Copyright (c) 2017 Jan Pluskal, Viliam Letavay
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Collections.Generic;
using System.Text;
using Thrift.Protocol;

namespace Netfox.SnooperMessenger.Protocol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MNMessagesSyncMessageMetadata : TBase
  {
    private MNMessagesSyncThreadKey _ThreadKey;
    private string _MessageId;
    private long _OfflineThreadingId;
    private long _ActorFbId;
    private long _Timestamp;
    private bool _ShouldBuzzDevice;
    private string _AdminText;
    private List<string> _Tags;

    public MNMessagesSyncThreadKey ThreadKey
    {
      get
      {
        return _ThreadKey;
      }
      set
      {
        __isset.ThreadKey = true;
        this._ThreadKey = value;
      }
    }

    public string MessageId
    {
      get
      {
        return _MessageId;
      }
      set
      {
        __isset.MessageId = true;
        this._MessageId = value;
      }
    }

    public long OfflineThreadingId
    {
      get
      {
        return _OfflineThreadingId;
      }
      set
      {
        __isset.OfflineThreadingId = true;
        this._OfflineThreadingId = value;
      }
    }

    public long ActorFbId
    {
      get
      {
        return _ActorFbId;
      }
      set
      {
        __isset.ActorFbId = true;
        this._ActorFbId = value;
      }
    }

    public long Timestamp
    {
      get
      {
        return _Timestamp;
      }
      set
      {
        __isset.Timestamp = true;
        this._Timestamp = value;
      }
    }

    public bool ShouldBuzzDevice
    {
      get
      {
        return _ShouldBuzzDevice;
      }
      set
      {
        __isset.ShouldBuzzDevice = true;
        this._ShouldBuzzDevice = value;
      }
    }

    public string AdminText
    {
      get
      {
        return _AdminText;
      }
      set
      {
        __isset.AdminText = true;
        this._AdminText = value;
      }
    }

    public List<string> Tags
    {
      get
      {
        return _Tags;
      }
      set
      {
        __isset.Tags = true;
        this._Tags = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool ThreadKey;
      public bool MessageId;
      public bool OfflineThreadingId;
      public bool ActorFbId;
      public bool Timestamp;
      public bool ShouldBuzzDevice;
      public bool AdminText;
      public bool Tags;
    }

    public MNMessagesSyncMessageMetadata() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Struct) {
                ThreadKey = new MNMessagesSyncThreadKey();
                ThreadKey.Read(iprot);
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.String) {
                MessageId = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I64) {
                OfflineThreadingId = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 4:
              if (field.Type == TType.I64) {
                ActorFbId = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 5:
              if (field.Type == TType.I64) {
                Timestamp = iprot.ReadI64();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 6:
              if (field.Type == TType.Bool) {
                ShouldBuzzDevice = iprot.ReadBool();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 7:
              if (field.Type == TType.String) {
                AdminText = iprot.ReadString();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 9:
              if (field.Type == TType.List) {
                {
                  Tags = new List<string>();
                  TList _list22 = iprot.ReadListBegin();
                  for( int _i23 = 0; _i23 < _list22.Count; ++_i23)
                  {
                    string _elem24;
                    _elem24 = iprot.ReadString();
                    Tags.Add(_elem24);
                  }
                  iprot.ReadListEnd();
                }
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("MNMessagesSyncMessageMetadata");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (ThreadKey != null && __isset.ThreadKey) {
          field.Name = "ThreadKey";
          field.Type = TType.Struct;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          ThreadKey.Write(oprot);
          oprot.WriteFieldEnd();
        }
        if (MessageId != null && __isset.MessageId) {
          field.Name = "MessageId";
          field.Type = TType.String;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(MessageId);
          oprot.WriteFieldEnd();
        }
        if (__isset.OfflineThreadingId) {
          field.Name = "OfflineThreadingId";
          field.Type = TType.I64;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(OfflineThreadingId);
          oprot.WriteFieldEnd();
        }
        if (__isset.ActorFbId) {
          field.Name = "ActorFbId";
          field.Type = TType.I64;
          field.ID = 4;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(ActorFbId);
          oprot.WriteFieldEnd();
        }
        if (__isset.Timestamp) {
          field.Name = "Timestamp";
          field.Type = TType.I64;
          field.ID = 5;
          oprot.WriteFieldBegin(field);
          oprot.WriteI64(Timestamp);
          oprot.WriteFieldEnd();
        }
        if (__isset.ShouldBuzzDevice) {
          field.Name = "ShouldBuzzDevice";
          field.Type = TType.Bool;
          field.ID = 6;
          oprot.WriteFieldBegin(field);
          oprot.WriteBool(ShouldBuzzDevice);
          oprot.WriteFieldEnd();
        }
        if (AdminText != null && __isset.AdminText) {
          field.Name = "AdminText";
          field.Type = TType.String;
          field.ID = 7;
          oprot.WriteFieldBegin(field);
          oprot.WriteString(AdminText);
          oprot.WriteFieldEnd();
        }
        if (Tags != null && __isset.Tags) {
          field.Name = "Tags";
          field.Type = TType.List;
          field.ID = 9;
          oprot.WriteFieldBegin(field);
          {
            oprot.WriteListBegin(new TList(TType.String, Tags.Count));
            foreach (string _iter25 in Tags)
            {
              oprot.WriteString(_iter25);
            }
            oprot.WriteListEnd();
          }
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("MNMessagesSyncMessageMetadata(");
      bool __first = true;
      if (ThreadKey != null && __isset.ThreadKey) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ThreadKey: ");
        __sb.Append(ThreadKey== null ? "<null>" : ThreadKey.ToString());
      }
      if (MessageId != null && __isset.MessageId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("MessageId: ");
        __sb.Append(MessageId);
      }
      if (__isset.OfflineThreadingId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("OfflineThreadingId: ");
        __sb.Append(OfflineThreadingId);
      }
      if (__isset.ActorFbId) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ActorFbId: ");
        __sb.Append(ActorFbId);
      }
      if (__isset.Timestamp) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Timestamp: ");
        __sb.Append(Timestamp);
      }
      if (__isset.ShouldBuzzDevice) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("ShouldBuzzDevice: ");
        __sb.Append(ShouldBuzzDevice);
      }
      if (AdminText != null && __isset.AdminText) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("AdminText: ");
        __sb.Append(AdminText);
      }
      if (Tags != null && __isset.Tags) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Tags: ");
        __sb.Append(Tags);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
