// Copyright (c) 2017 Jan Pluskal, Viliam Letavay
//
//Licensed under the Apache License, Version 2.0 (the "License");
//you may not use this file except in compliance with the License.
//You may obtain a copy of the License at
//
//    http://www.apache.org/licenses/LICENSE-2.0
//
//Unless required by applicable law or agreed to in writing, software
//distributed under the License is distributed on an "AS IS" BASIS,
//WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or implied.
//See the License for the specific language governing permissions and
//limitations under the License.

/**
 * Autogenerated by Thrift Compiler (0.9.3)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
using System;
using System.Text;
using Thrift.Protocol;

namespace Netfox.SnooperMessenger.Protocol
{

  #if !SILVERLIGHT
  [Serializable]
  #endif
  public partial class MNMessagesSyncNotificationDoNotDisturbRange : TBase
  {
    private sbyte _Days;
    private short _StartMinutes;
    private short _DurationMinutes;

    public sbyte Days
    {
      get
      {
        return _Days;
      }
      set
      {
        __isset.Days = true;
        this._Days = value;
      }
    }

    public short StartMinutes
    {
      get
      {
        return _StartMinutes;
      }
      set
      {
        __isset.StartMinutes = true;
        this._StartMinutes = value;
      }
    }

    public short DurationMinutes
    {
      get
      {
        return _DurationMinutes;
      }
      set
      {
        __isset.DurationMinutes = true;
        this._DurationMinutes = value;
      }
    }


    public Isset __isset;
    #if !SILVERLIGHT
    [Serializable]
    #endif
    public struct Isset {
      public bool Days;
      public bool StartMinutes;
      public bool DurationMinutes;
    }

    public MNMessagesSyncNotificationDoNotDisturbRange() {
    }

    public void Read (TProtocol iprot)
    {
      iprot.IncrementRecursionDepth();
      try
      {
        TField field;
        iprot.ReadStructBegin();
        while (true)
        {
          field = iprot.ReadFieldBegin();
          if (field.Type == TType.Stop) { 
            break;
          }
          switch (field.ID)
          {
            case 1:
              if (field.Type == TType.Byte) {
                Days = iprot.ReadByte();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 2:
              if (field.Type == TType.I16) {
                StartMinutes = iprot.ReadI16();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            case 3:
              if (field.Type == TType.I16) {
                DurationMinutes = iprot.ReadI16();
              } else { 
                TProtocolUtil.Skip(iprot, field.Type);
              }
              break;
            default: 
              TProtocolUtil.Skip(iprot, field.Type);
              break;
          }
          iprot.ReadFieldEnd();
        }
        iprot.ReadStructEnd();
      }
      finally
      {
        iprot.DecrementRecursionDepth();
      }
    }

    public void Write(TProtocol oprot) {
      oprot.IncrementRecursionDepth();
      try
      {
        TStruct struc = new TStruct("MNMessagesSyncNotificationDoNotDisturbRange");
        oprot.WriteStructBegin(struc);
        TField field = new TField();
        if (__isset.Days) {
          field.Name = "Days";
          field.Type = TType.Byte;
          field.ID = 1;
          oprot.WriteFieldBegin(field);
          oprot.WriteByte(Days);
          oprot.WriteFieldEnd();
        }
        if (__isset.StartMinutes) {
          field.Name = "StartMinutes";
          field.Type = TType.I16;
          field.ID = 2;
          oprot.WriteFieldBegin(field);
          oprot.WriteI16(StartMinutes);
          oprot.WriteFieldEnd();
        }
        if (__isset.DurationMinutes) {
          field.Name = "DurationMinutes";
          field.Type = TType.I16;
          field.ID = 3;
          oprot.WriteFieldBegin(field);
          oprot.WriteI16(DurationMinutes);
          oprot.WriteFieldEnd();
        }
        oprot.WriteFieldStop();
        oprot.WriteStructEnd();
      }
      finally
      {
        oprot.DecrementRecursionDepth();
      }
    }

    public override string ToString() {
      StringBuilder __sb = new StringBuilder("MNMessagesSyncNotificationDoNotDisturbRange(");
      bool __first = true;
      if (__isset.Days) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("Days: ");
        __sb.Append(Days);
      }
      if (__isset.StartMinutes) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("StartMinutes: ");
        __sb.Append(StartMinutes);
      }
      if (__isset.DurationMinutes) {
        if(!__first) { __sb.Append(", "); }
        __first = false;
        __sb.Append("DurationMinutes: ");
        __sb.Append(DurationMinutes);
      }
      __sb.Append(")");
      return __sb.ToString();
    }

  }

}
